# Tugas kecil 2: Eksplorasi Scikit-Learn pada Jupyter Notebook
---
Oleh: Ivan Jonathan (13516059) dan Mochamad Alghifari (13516038)

## Overview
    1. Import Library yang dibutuhkan
    2. Pembacaan Dataset Training
        2.1 Dataset Iris
        2.2 Dataset Play Tennis
    3. Pembelajaran Dataset Iris dengan Skema Full Training 
        3.1 Naïve Bayes
        3.2 DTL
        3.3 kNN
        3.4 Neural Network MLP
    4. Pembelajaran Dataset Iris dengan Skema Split Training 90%, test 10%, dan menampilkan kinerja serta confusion matrix
        4.1 Membagi dataset menjadi 10% untuk Test
        4.2 Naïve Bayes
        4.3 DTL
        4.4 kNN
        4.5 Neural Network MLP
    5. Pembelajaran Dataset Iris dengan Skema 10-Fold Cross Validation, dan menampilkan kinerjanya.
        5.1 Naïve Bayes
        5.2 DTL
        5.3 kNN
        5.4 Neural Network MLP
    6. Penyimpanan Model ke File External
    7. Sumber

## 1. Import Library yang dibutuhkan

In [1]:
#Import library untuk proses data
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse
import numpy as np

#Import library yang dibutuhkan untuk pembelajaran
import pandas as pd
from sklearn import datasets, metrics, neighbors, tree
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import GaussianNB
import graphviz 
from sklearn.neural_network import MLPClassifier
from sklearn.externals import joblib

ImportError: No module named graphviz

In [11]:
gnb = GaussianNB()
dtl = tree.DecisionTreeClassifier()
kNN = neighbors.KNeighborsClassifier(5, weights='uniform')
mlp = MLPClassifier(solver='lbfgs', alpha=1e-5,
                     hidden_layer_sizes=(5, 2), random_state=1)

## 2. Pembacaan Dataset Training

### 2.1 Dataset Iris

In [12]:
dfiris = datasets.load_iris()

#### Iris attributes

In [13]:
dfiris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

#### Iris data

In [14]:
dfiris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

#### Iris target

In [15]:
dfiris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 2.2 Dataset Play Tennis

#### Data play tennis

Karena training data berbentuk string maka harus dirubah menjadi bentuk integer dengan masing-masing fitur:

outlook: {'sunny':0,'rainy':1,'overcast':2}<br>
temperature: {'hot':0,'mild':1,'cool':2}<br>
humidity: {'normal':0,'high':1}<br>
windy: {'FALSE':0, 'TRUE':1}<br>
play: {'no':0,'yes':1}

In [16]:
#Lokasi dapat diganti sesuai dengan lokasi file csv di direktori anda
#/home/alghifari/Documents/Tucil2-AI/weather.nominal.csv
dfpt = pd.read_csv('/home/mark/Documents/File Semester 5/Artificial Intelligence/Tucil 2/weather.nominal.csv',
                  sep=',',
                  header=None,
                  names=['outlook','temperature', 'humidity', 'windy','play'])
dfpt = dfpt[1:]

#Convert str to int for prediction
dfpt['outlook'] = dfpt.outlook.map({'sunny':0,'rainy':1,'overcast':2})
dfpt['temperature'] = dfpt.temperature.map({'hot':0,'mild':1,'cool':2})
dfpt['humidity'] = dfpt.humidity.map({'normal':0,'high':1})
dfpt['windy'] = dfpt.windy.map({'FALSE':0, 'TRUE':1})
dfpt['play'] = dfpt.play.map({'no':0,'yes':1})

dfpt

outlook  temperature  humidity  windy  play
1         0            0         1      0     0
2         0            0         1      1     0
3         2            0         1      0     1
4         1            1         1      0     1
5         1            2         0      0     1
6         1            2         0      1     0
7         2            2         0      1     1
8         0            1         1      0     0
9         0            2         0      0     1
10        1            1         0      0     1
11        0            1         0      1     1
12        2            1         1      1     1
13        2            0         0      0     1
14        1            1         1      1     0

In [17]:
dfpt_data = dfpt.iloc[:,0:4].values
dfpt_data

array([[0, 0, 1, 0],
       [0, 0, 1, 1],
       [2, 0, 1, 0],
       [1, 1, 1, 0],
       [1, 2, 0, 0],
       [1, 2, 0, 1],
       [2, 2, 0, 1],
       [0, 1, 1, 0],
       [0, 2, 0, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 1],
       [2, 1, 1, 1],
       [2, 0, 0, 0],
       [1, 1, 1, 1]])

#### Play tennis target

In [18]:
dfpt_target = dfpt.iloc[:, [4]].values.ravel()
dfpt_target

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

## 3. Pembelajaran Dataset Iris dengan Skema Full Training

### 3.1 Naïve Bayes

In [19]:
iris = gnb.fit(dfiris.data, dfiris.target)
print("Model: ")
print("Probabilitas tiap kelas: ")
print(iris.class_prior_)
print
print("Rata-rata fitur per kelas: ")
print(iris.theta_)
print
print("Probabilitas tiap fitur bila diberikan kelas: ")
print(iris.sigma_)

Model: 
Probabilitas tiap kelas: 
[0.33333333 0.33333333 0.33333333]

Rata-rata fitur per kelas: 
[[5.006 3.418 1.464 0.244]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]

Probabilitas tiap fitur bila diberikan kelas: 
[[0.121764 0.142276 0.029504 0.011264]
 [0.261104 0.0965   0.2164   0.038324]
 [0.396256 0.101924 0.298496 0.073924]]


### 3.2 Decision Tree Learning

In [20]:
dtl_model = dtl.fit(dfiris.data, dfiris.target)

dot_data = tree.export_graphviz(dtl_model, out_file=None, 
                         feature_names=dfiris.feature_names,  
                         class_names=dfiris.target_names,  
                         filled=True, rounded=True,  
                         special_characters=True)

graph = graphviz.Source(dot_data)


NameError: name 'graphviz' is not defined

In [ ]:
# Export to iris_dtl.pdf
graph.render("iris_dtl")

In [ ]:
# Visualize decision tree learning model
graph 

### 3.3 *kNN*

Pada *k-Nearest Neighbor* (*kNN*) tidak menghasilkan model.

In [ ]:
kNN.fit(dfiris.data, dfiris.target)

### 3.4 Neural Network MLP

In [ ]:
mlp_model = mlp.fit(dfiris.data, dfiris.target)
mlp_model

## 4. Pembelajaran Dataset Iris dengan Skema Split Training 90%, Test 10%, dan Menampilkan kinerja serta confusion matrix


### 4.1 Membagi dataset menjadi 10% untuk Test

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(dfiris.data, dfiris.target, test_size=0.1)

### 4.2 Naïve Bayes

In [ ]:
bayes_model = gnb.fit(X_train, y_train)
prediction_bayes = bayes_model.predict(X_test)
precision_bayes = metrics.precision_score(y_test, prediction_bayes, average=None) * 100
recall_bayes = metrics.recall_score(y_test, prediction_bayes, average=None) * 100

print("Kinerja: ")
print("\t1. Akurasi: %f" % (np.mean(prediction_bayes == y_test) * 100) + "%")
print("\t2. Presisi tiap kelas:")
for i in range(3):
    print("\t\t" + dfiris.target_names[i] + ": " + str(precision_bayes[i]) + "%")
print
print("\t3. Recall setiap kelas:")
for i in range(3):
    print(dfiris.target_names[i] + ": " + str(recall_bayes[i]) + "%")
print

print
print("Confusion Matrix: ")
print(metrics.confusion_matrix(y_test, prediction_bayes))  

### 4.3 Decision Tree Learning

In [ ]:
dtl_model = dtl.fit(X_train, y_train)
prediction_dtl = dtl_model.predict(X_test)
precision_dtl = metrics.precision_score(y_test, prediction_dtl, average=None) * 100
recall_dtl = metrics.recall_score(y_test, prediction_dtl, average=None) * 100

print("Kinerja: ")
print("\t1. Akurasi: %f" % (np.mean(prediction_dtl == y_test) * 100) + "%")
print("\t2. Presisi tiap kelas:")
for i in range(3):
    print("\t\t" + dfiris.target_names[i] + ": " + str(precision_dtl[i]) + "%")
print("\t3. Recall setiap kelas:")
for i in range(3):
    print(dfiris.target_names[i] + ": " + str(recall_dtl[i]) + "%")
print

print
print("Confusion Matrix: ")
print(metrics.confusion_matrix(y_test, prediction_dtl))  

### 4.4 *kNN*

In [ ]:
kNN.fit(X_train, y_train)
prediction_knn = kNN.predict(X_test)
precision_knn = metrics.precision_score(y_test, prediction_knn, average=None) * 100
recall_knn = metrics.recall_score(y_test, prediction_knn, average=None) * 100

print("Kinerja: ")
print("\t1. Akurasi: %f" % (np.mean(prediction_knn == y_test) * 100) + "%")
print("\t2. Presisi tiap kelas:")
for i in range(3):
    print("\t\t" + dfiris.target_names[i] + ": " + str(precision_knn[i]) + "%")
print("\t3. Recall setiap kelas:")
for i in range(3):
    print(dfiris.target_names[i] + ": " + str(recall_knn[i]) + "%")
print

print
print("Confusion Matrix: ")
print(metrics.confusion_matrix(y_test, prediction_knn))  

### 4.5 Neural Network MLP

In [ ]:
mlp_model = mlp.fit(X_train, y_train)
prediction_mlp = mlp_model.predict(X_test)
precision_mlp = metrics.precision_score(y_test, prediction_mlp, average=None) * 100
recall_mlp = metrics.recall_score(y_test, prediction_mlp, average=None) * 100

print("Kinerja: ")
print("\t1. Akurasi: %f" % (np.mean(prediction_mlp == y_test) * 100) + "%")
print("\t2. Presisi tiap kelas:")
for i in range(3):
    print("\t\t" + dfiris.target_names[i] + ": " + str(precision_mlp[i]) + "%")
print("\t3. Recall setiap kelas:")
for i in range(3):
    print(dfiris.target_names[i] + ": " + str(recall_mlp[i]) + "%")
print

print
print("Confusion Matrix: ")
print(metrics.confusion_matrix(y_test, prediction_mlp))  

## 5. Pembelajaran Dataset Iris dengan Skema 10-Fold Cross Validation, dan menampilkan kinerjanya.

### 5.1 Naïve Bayes

In [ ]:
scores_bayes = cross_val_score(gnb, dfiris.data, dfiris.target, cv=10)

i = 1
print("Kinerja: ")
for score in scores_bayes:
    print("Fold ke-%d" % i + " = %f" % score)
    i+=1
print
print("Rata-rata = %f"% np.mean(scores_bayes))

### 5.2 Decision Tree Learning

In [ ]:
scores_dtl = cross_val_score(dtl, dfiris.data, dfiris.target, cv=10)

i = 1
print("Kinerja: ")
for score in scores_dtl:
    print("Fold ke-%d" % i + " = %f" % score)
    i+=1
print
print("Rata-rata = %f"% np.mean(scores_dtl))

### 5.3 *kNN*

In [ ]:
scores_knn = cross_val_score(kNN, dfiris.data, dfiris.target, cv=10)

i = 1
print("Kinerja: ")
for score in scores_knn:
    print("Fold ke-%d" % i + " = %f" % score)
    i+=1
print
print("Rata-rata = %f"% np.mean(scores_knn))

### 5.4 Neural Network MLP

In [ ]:
scores_mlp = cross_val_score(mlp, dfiris.data, dfiris.target, cv=10)

i = 1
print("Kinerja: ")
for score in scores_mlp:
    print("Fold ke-%d" % i + " = %f" % score)
    i+=1
print
print("Rata-rata = %f"% np.mean(scores_mlp))

## 6. Penyimpanan Model ke File External

In [22]:
joblib.dump(gnb, 'iris_NB.mdl')
joblib.dump(dtl, 'iris_DT.mdl')
joblib.dump(kNN, 'iris_kNN.mdl')
joblib.dump(mlp, 'iris_MLP.mdl')

['iris_MLP.mdl']

## 7. Sumber

Tom Mitchell, Machine Learning, 1999, Textbook